### ISSUE TITLE
checklist

### ISSUE THREAD

**Issue by okj203** [humormee/PaintSocial#1]
- [x] include heroku deployment in the mvp list
- [x] include user auth in the mvp list
- [x] each item in the mvp list needs more details - which crud functionalities are you working on for each entity?
- [x] list the technical challenges you anticipate to face
- [ ] specify day-by-day breakdown for each individual
